export const berthData = [
  {
    deck: 'lower Deck',
    seatNo: 'L1',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'lower Deck',
    seatNo: 'L2',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'lower Deck',
    seatNo: 'L3',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'lower Deck',
    seatNo: 'L4',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'lower Deck',
    seatNo: 'L5',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'lower Deck',
    seatNo: 'L6',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'lower Deck',
    seatNo: 'L7',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'lower Deck',
    seatNo: 'L8',
    seatFare: 440,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U9',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U10',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U11',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U12',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U13',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U14',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U15',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
  {
    deck: 'upper Deck',
    seatNo: 'U16',
    seatFare: 340,
    status: 'available',
    bookedGender: 'male',
  },
];
