export const berthData = [
  {
    deck: 'lower Deck',
    seatNo: 1,
    seatFare: 440,
    bookedGender: 'male',
    status: 'unavailable',
  },
  {
    deck: 'lower Deck',
    seatNo: 2,
    seatFare: 440,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'lower Deck',
    seatNo: 3,
    seatFare: 440,
    bookedGender: 'female',
    status: 'available',
  },
  {
    deck: 'lower Deck',
    seatNo: 4,
    seatFare: 440,
    bookedGender: 'female',
    status: 'unavailable',
  },
  {
    deck: 'lower Deck',
    seatNo: 5,
    seatFare: 440,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'lower Deck',
    seatNo: 6,
    seatFare: 440,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'lower Deck',
    seatNo: 7,
    seatFare: 440,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'lower Deck',
    seatNo: 8,
    seatFare: 440,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 9,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 10,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 11,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 12,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 13,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 14,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 15,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
  {
    deck: 'upper Deck',
    seatNo: 16,
    seatFare: 340,
    bookedGender: 'male',
    status: 'available',
  },
];
