export const seatDetails = [
  {
    id: '1',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '2',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '3',
    status: 'unavailable',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '4',
    status: 'available',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '5',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '6',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '7',
    status: 'available',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '8',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '9',
    status: 'available',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '10',
    status: 'unavailable',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '11',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '12',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '13',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '14',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '15',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '16',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '17',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '18',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '19',
    status: 'unavailable',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '20',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '21',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '22',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '23',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '24',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '25',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '26',
    status: 'unavailable',
    bookedGender: 'male',
    selected: false,
  },
  {
    id: '27',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '28',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '29',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '30',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '31',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
  {
    id: '32',
    status: 'available',
    bookedGender: 'female',
    selected: false,
  },
];

export const detailsContainer = [
  {
    classname: 'femaleAvailable detailsMain femaleBorder',
    text: 'Female',
  },
  {
    classname: 'available detailsMain',
    text: 'Available',
  },
  {
    classname: 'femaleUnavailable detailsMain bookedColor',
    text: 'Booked',
  },
];
